theme: jekyll-theme-minimal
title: AI Search Pro
description: 精选最佳 AI 工具和应用

# 多语言配置
languages: ["zh", "en"]
default_lang: "zh"
exclude_from_localization: ["assets", "css", "js"]

# 语言特定配置
t:
  zh:
    title: "AI Search Pro"
    description: "精选最佳 AI 工具和应用"
    tagline: "精选最佳 AI 工具与应用 · 每日更新"
    subtitle: "按使用场景与工具类型分类，帮助你以更低成本、更高效率找到合适的 AI 解决方案。支持中文优先、免登录/免信用卡筛选，覆盖 ChatGPT、Claude、Gemini、Midjourney、SDXL 等主流模型。"
    nav:
      featured: "热门"
      updates: "更新"
      use_cases: "使用场景"
      tool_types: "工具类型"
      collections: "合集"
      guides: "教程"
    buttons:
      discover: "立即发现工具"
      submit: "提交/推荐工具"
      search: "搜索"
    search_placeholder: "搜索关键词（如：写作、绘图、字幕、开源、中文、免费）"
    sections:
      featured: "热门推荐 Featured Picks"
      featured_sub: "人工精选/热度靠前 · 快速上手"
      updates: "今日/本周更新 Today / This Week"
      updates_sub: "持续新增与校准，体现"每日更新"的承诺"
      use_cases: "使用场景 Use Cases"
      use_cases_sub: "按真实需求组织，更贴近新手心智"
      tool_types: "工具类型 Tool Types"
      tool_types_sub: "按产品形态/使用方式划分"
      collections: "合集与对比 Collections & Comparisons"
      guides: "教程与指南 Guides & Tutorials"
    footer: "© AI Search Pro · 每日更新"
  en:
    title: "AI Search Pro"
    description: "Curated Best AI Tools and Applications"
    tagline: "Curated Best AI Tools & Applications · Daily Updates"
    subtitle: "Organized by use cases and tool types to help you find the right AI solutions with lower cost and higher efficiency. Supports Chinese-first, no-login/no-credit-card filtering, covering mainstream models like ChatGPT, Claude, Gemini, Midjourney, SDXL."
    nav:
      featured: "Featured"
      updates: "Updates"
      use_cases: "Use Cases"
      tool_types: "Tool Types"
      collections: "Collections"
      guides: "Guides"
    buttons:
      discover: "Discover Tools Now"
      submit: "Submit/Recommend Tools"
      search: "Search"
    search_placeholder: "Search keywords (e.g.: writing, drawing, subtitles, open source, Chinese, free)"
    sections:
      featured: "Featured Picks 热门推荐"
      featured_sub: "Hand-picked / Top trending · Quick start"
      updates: "Today / This Week 今日/本周更新"
      updates_sub: "Continuous additions and calibrations, demonstrating our 'daily update' commitment"
      use_cases: "Use Cases 使用场景"
      use_cases_sub: "Organized by real needs, more beginner-friendly"
      tool_types: "Tool Types 工具类型"
      tool_types_sub: "Categorized by product form/usage method"
      collections: "Collections & Comparisons 合集与对比"
      guides: "Guides & Tutorials 教程与指南"
    footer: "© AI Search Pro · Daily Updates"